server:
    address: 0.0.0.0
    port: 8080

spring:
    profiles:
        active: cloud

integraciones:
    micro-cuentas:
        url: http://localhost:8082
    cuenta-bancaria-corporativa:
        id: 1

---

spring:
    config:
        activate:
            on-profile: test_unitarios
    datasource:
        url: jdbc:h2:mem:test-db
        username: user
        password: pass
        driver-class-name: org.h2.Driver
    jpa:
        hibernate:
            ddl-auto: create-drop

---

spring:
    config:
        activate:
            on-profile: test_integracion
    datasource:
        url: jdbc:postgresql://localhost:5432/inversion
        username: admin
        password: ejemplo123
        driver-class-name: org.postgresql.Driver
    jpa:
        hibernate:
            ddl-auto: update
    
logging:
    level:
        feign:
            logger: DEBUG

---

spring:
    config:
        activate:
            on-profile: cloud
    datasource:
        url: jdbc:postgresql://${DB_HOST:host.docker.internal}:${DB_PORT:5432}/${DB_NAME:inversion}
        username: ${DB_USER:admin}
        password: ${DB_password:ejemplo123}
        driver-class-name: org.postgresql.Driver
    jpa:
        hibernate:
            ddl-auto: update

integraciones:
    micro-cuentas:
        url: http://${CUENTAS_HOST:host.docker.internal}:${CUENTAS_PORT:8080}