services:
  inversion-db:
    image: 'postgres:latest'
    environment:
      - 'POSTGRES_DB=inversion'
      - 'POSTGRES_PASSWORD=ejemplo123'
      - 'POSTGRES_USER=admin'
    ports:
      - '5432:5432'
