services:
  inversion-db:
    image: 'postgres:latest'
    environment:
      - 'POSTGRES_DB=inversion'
      - 'POSTGRES_PASSWORD=ejemplo123'
      - 'POSTGRES_USER=admin'
    ports:
      - '5432:5432'
  micro-cuentas-db:
    image: 'postgres:latest'
    environment:
      - 'POSTGRES_DB=cuentabancaria'
      - 'POSTGRES_PASSWORD=ejemplo123'
      - 'POSTGRES_USER=admin'
    networks:
      - isolated
  micro-cuentas:
    image: 'jdarguello10/spring-taller6-cuenta:latest'
    environment:
      - DB_HOST=micro-cuentas-db
      - DB_PORT=5432
    ports:
      - '8082:8080'
    networks:
      - isolated

networks:
  isolated:
    driver: bridge