name: CI Workflow

on:
  push:
    branches:
      - main
    paths:
      - 'InversionVirtual/**'

jobs:
  build:
    uses: jdarguello/Spring-Taller6-InversionVirtual/.github/workflows/build.yaml@main
    secrets:
      SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
  
  artifact:
    needs:
    - build
    uses: jdarguello/Spring-Taller6-InversionVirtual/.github/workflows/artifact.yaml@main
    secrets:
      DOCKER_HUB_USERNAME: ${{ secrets.DOCKER_HUB_USERNAME }}
      DOCKER_HUB_TOKEN: ${{ secrets.DOCKER_HUB_TOKEN }}